baseurl = "http://anastasiyaig.github.io"
title = "anastasiya"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

[markup.highlight]
style = "github-dark"

[params]
  author = "Anastasiya Semiankevich"
  info = "Lead QA Engineer"
  description = "Anastasiya Semiankevich's personal website"
  keywords = "qa,personal,testing"
  avatarurl = "https://img.hhcdn.ru/photo/749838066.jpeg?t=1710861912&h=TWFuu-omZ_RgiI5OCDyWDw"
  since = 2024

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 2
  url = "https://github.com/anastasiyaig"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/anastasiya-semiankevich/"
[[params.social]]
  name = "Telegram"
  icon = "fa fa-telegram fa-2x"
  weight = 2
  url = "https://t.me/in_nocent"

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages.en]
languageName = ':uk:'
[[languages.en.menu.main]]
    name = "About"
    weight = 2
    url = "about/"
[[languages.en.menu.main]]
    name = "Courses"
    weight = 2
    url = "courses/"

[languages.ru]
languageName = ':ru:'
    title = "Анастасия"
[languages.ru.params]
    author = "Анастасия Семенкевич"
    info = "Ведущий инженер по тестированию"
[[languages.ru.menu.main]]
    name = "Обо мне"
    weight = 2
    url = "about/"
[[languages.ru.menu.main]]
    name = "Курсы"
    weight = 2
    url = "courses/"

